# Generated by Django 5.2 on 2025-05-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='Vegetable_Images'),
        ),
    ]
