# Generated by Django 5.2 on 2025-05-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_producthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='movement_type',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('purchased', 'Purchased')], default='added', max_length=50),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='movement_type',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated')], default='added', max_length=50),
        ),
    ]
