# Generated by Django 5.2 on 2025-05-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_orderhistory_movement_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='product',
        ),
    ]
