# Generated by Django 5.2 on 2025-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_orderhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='user',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
