# Generated by Django 5.2 on 2025-05-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_orderhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='action',
        ),
    ]
